### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui-docs#1]
- [x] Add script to update `.all-membersrc`
- [x] Add script to update `.all-sponsorsrc`
- [x] Update `.all-contributorsrc` to include only those who contributed to docs
- [x] Add `.github` actions and workflows related to docs
- [x] Add Vercel Github app
