### ISSUE TITLE
Add case studies

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui-docs#639]
### Subject

[New]: Case studies

### Description

I'd like us to introduce a new page on the website that covers case studies of consumers who use Chakra UI at scale. This is a primary element to convince potential users to use Chakra UI (the showcase being the secondary element).

**Some ideas:**
https://www.radix-ui.com/case-studies
https://vercel.com/customers

**Tasks:**
- [ ]  We need to craft a set of open-ended questions that we intend to ask.
- [ ] Identify users who are willing to write case studies to explain their usage of Chakra UI.
- [ ] Group case study by industry and scope (design system, app, website, or all).
- [ ] Send out case studies
- [ ] Add a `/case-studies` page to the website

**Comment by TylerAPfledderer** [comment]
Possible questions to ask:
- Describe the types of projects you use ChakraUI with?
- What challenges did ChakraUI solve?
- How has ChakraUI contributed to the improved developer experience?
- What are your thoughts on the ChakraUI documentation?
- What other features or technologies has ChakraUI allowed you to create/use that you never thought were possible?
- What other feedback have you received from your dev team?

**Comment by TylerAPfledderer** [comment]
Not stale

**Comment by nikolovlazar** [comment]
I've compiled a list of questions (thanks @TylerAPfledderer!):

# Questions:

- Can you describe your project?
- What challenges did Chakra UI solve?
- What are your thoughts on the Chakra UI developer experience?
- What are your thoughts on the Chakra UI documentation?
- What are your thoughts on the community around Chakra UI?
- What other features or technologies has Chakra UI allowed you to create/use that you never thought were possible?

@segunadebayo can you take a look at these and add/remove/change anything if needed?
